__title__ = 'cookeroo'
__description__ = ''
__url__ = ''
__version__ = '0.0.1'
__author__ = 'Abhilash Kishore and Ayush Bihani'
__author_email__ = 'abhilash1in@gmail.com'
__copyright__ = 'Copyright 2020 Abhilash Kishore and Ayush Bihani'
